### ISSUE TITLE
Supplied software

### ISSUE THREAD

**Issue by Seo-Young** [OpenChain-KWG/Specification-Translation-KR#10]
supplied software는 공급 대상 소프트웨어라고 표현하니 어색한 느낌이 듭니다. 제공 대상? 이런 텀은 어떨까요? 
2.0 번역은 이미 끝난건가요? contribution 할게 뭐가 있는지 알려주세요.

**Comment by haksungjang** [comment]
"제공 대상 소프트웨어", "제공 소프트웨어", "배포 소프트웨어", "배포 대상 소프트웨어" 등의 용어를 고민하다가 다른 Contributor분께서 "공급 대상 소프트웨어"라는 용어가 법적으로 적절해보인다고 의견주셔서 결정한바 있습니다. 그래도 문서를 읽는 사람에게 어색한 표현은 고치는게 맞을것 같으니, 어떤 용어로 표현하는게 Supplied Software의 의미를 어색하지 않게 전달할 수 있을지 의견주세요!

2.0번역은 1차 완료되어 draft가 나온 상태이고, 다른 Contributor분께서 Review중에 있습니다. 지금 의견 주시면 검토하여 반영됩니다. 감사합니다. ^^

**Comment by Seo-Young** [comment]
draft는 현재 src 상에 영문 아래 적힌 한글 부분을 지칭하시는 건가요?

**Comment by haksungjang** [comment]
네, 맞습니다.

**Comment by Seo-Young** [comment]
우선은 그럼 공급 대상 소프트웨어로 진행하시죠. 이 이슈는 이로 종결하겠습니다.
