### ISSUE TITLE
오픈 소스 vs 오픈소스

### ISSUE THREAD

**Issue by Seo-Young** [OpenChain-KWG/Specification-Translation-KR#13]
'오픈소스'는 이미 대명사가 되었다고 할 수 있지 않을까요?
Open Source 라는 영어 단어에 맞추어 '오픈 소스' 라고 떼어 적는 것에 대해 논의해 보았으면 합니다. 
저는 '오픈소스'로 붙여쓰는 것이 좋다고 생각합니다. 의견을 듣고 싶습니다.

**Comment by haksungjang** [comment]
네, 의견 감사합니다. '오픈소스'로 붙여쓰는 것에 이견 없습니다. 전체적으로 한번에 싹 반영하겠습니다.
반영 후에 Close 하겠습니다. 
감사합니다.

**Comment by Seo-Young** [comment]
제가 모두 반영하였습니다. Close 하겠습니다.
