### ISSUE TITLE
release 일정

### ISSUE THREAD

**Issue by Seo-Young** [OpenChain-KWG/Specification-Translation-KR#25]
2.0 release 일정은 어떻게 되나요??

**Comment by haksungjang** [comment]
지난 주말에 박종백 변호사님께 review 요청 드린 상태입니다. review 완료 후 release 예정입니다.

**Comment by haksungjang** [comment]
여러 기여자분들의 도움으로 OpenChain Specification 2.0 한국어 번역 draft version이 완성되었습니다. : https://github.com/OpenChain-Project/Specification-Translation-KR/blob/master/translate/2.0/OpenChainSpec-2.0_Kor_draft.docx

draft version에 대해 8월말까지 의견 수렴 후 9월초에 정식 Release하겠습니다. 

감사합니다.
